### ISSUE TITLE
Android Manifest merge fails with tools:node="remove"

### ISSUE THREAD

**Issue by Skjalgsm** [bitstadium/HockeySDK-Unity-Android#11] opened 2016-11-18 10:27 UTC
Hi.

In order to remove the WRITE_EXTERNAL_STORAGE permission I am trying to add the tools:node="remove" to it in the main AndroidManifest file, but this fails the build.
![image](https://cloud.githubusercontent.com/assets/568589/20426961/d3fb495c-ad81-11e6-953b-8fc4f15e91c7.png)
[error.txt](https://github.com/bitstadium/HockeySDK-Unity-Android/files/599694/error.txt)

**Comment by chrwend** [comment] 2017-05-16 09:04
@Skjalgsm Is that still an issue? Wasn't able to reproduce it.

**Comment by TroubleMakerBen** [comment] 2017-07-24 18:16
@Skjalgsm let me know if you're still running into it.

**Comment by Skjalgsm** [comment] 2017-07-27 15:54
sure thing

**Comment by Noshire** [comment] 2017-08-03 11:07
I experience the same issue. I followed the guide provided here: https://support.hockeyapp.net/kb/client-integration-android/hockeyapp-for-android-sdk#4-7-1-removing-external-storage-permission and added the removal flag to the base custom manifest under Assets/Plugins/Android/AndroidManifest.xml as described (of course also referencing the tools package):

`  <uses-permission
    android:name="android.permission.WRITE_EXTERNAL_STORAGE"
    tools:node="remove" />`

[merge_error.txt](https://github.com/bitstadium/HockeySDK-Unity-Android/files/1196934/merge_error.txt)

**Comment by bmourat** [comment] 2017-09-26 10:41
Hi @Noshire 

Could you please share the contents of your manifest file?

Best,
Murat

**Comment by TroubleMakerBen** [comment] 2017-10-05 18:13
Hey folks,

Please let me know if you still see this issue. If I don't hear back until next week, I'm gonna close this.

Also, thanks for using HockeyApp! =)

**Comment by codemaster** [comment] 2017-10-10 01:00
Still having this issue, even after attempting the `tools:node="remove"` addition:

Trying to merge incompatible /manifest/uses-permission[@name=android.permission.WRITE_EXTERNAL_STORAGE] element:
```  <uses-permission
--    @android:maxSdkVersion="18"
--    @android:name="android.permission.WRITE_EXTERNAL_STORAGE">
--</uses-permission>
  <uses-permission
++    @android:name="android.permission.WRITE_EXTERNAL_STORAGE">
++</uses-permission>
++(end reached)```

**Comment by MatkovIvan** [comment] 2017-10-12 13:01
Hi @codemaster 

Looks like your issue is different a bit. I guessed why this could happen, but unfortunately, I cannot reproduce this.
Could you please try to add `android:maxSdkVersion="18"` in your manifest? This will remove differences and merge in unity should finish fine.
If it doesn't help could you please share reproduction sample?
JFYI: [I've also updated manifest](https://github.com/bitstadium/HockeySDK-Unity-Android/pull/23/commits/34afbd4fc69be0891683bf493873f34b3b2d41c3) to match with native SDK. Hope that help to avoid issues like that in the future versions "out the box".

**Comment by codemaster** [comment] 2017-10-13 11:26
I tried using the updated manifest file that you linked, but I am encountering the same exact error. It's a bit bizarre for sure. I made sure to nuke my `Temp` directory before trying to build, to sanity-check.

As another sanity check, I looked for XML files containing `"WRITE_EXTERNAL_STORAGE"` in my project and other than the XML from the Hockey SDK, I found two in `Temp/StagingArea`:
`./Temp/StagingArea/android-libraries/HockeySDK-5.0.2/AndroidManifest.xml`
`./Temp/StagingArea/android-libraries/hockeysdk-unity-5.0.0/AndroidManifest.xml`

Both of these files did _not_ have the updated `package` attribute, as per the included instructions, but were still in the `net.hockeyapp.android` package. The one in the `HockeySDK-5.0.2` path has the entry with `android:maxSdkVersion="18"`, while the one in `hockeysdk-unity-5.0.2` has it _without_ the `android:maxSdkVersion="18"`.

I paused for a moment and realized the Hockey App plugin from the Unity Asset Store includes *two* AAR files - one for version 5.0.0 and another for version 5.0.2. I deleted the one for version 5.0.0 and rebuilt again - this time with no errors! 👍 

I think whoever is maintaining the Unity Asset Store entry for the HockeyApp Android SDK needs to ensure they aren't including two AARs!

**Comment by MatkovIvan** [comment] 2017-10-13 11:33
My fix isn't released yet, that's why `AndroidManifest.xml` for `hockeysdk-unity` is wrong. But both aars are necessary - the first one is native sdk and the second one is unity wrapper.

**Comment by codemaster** [comment] 2017-10-13 11:34
Hmm interesting that removing one fixes it. Is the best course of action here to wait for the new version with the updated XML?

**Comment by MatkovIvan** [comment] 2017-10-13 11:45
Errors will be at runtime. Could you please share reproduction sample? It doesn't reproduce for me and I want to check that my fix really works and next version will be fine.

**Comment by pleribus** [comment] 2017-10-23 14:17
Having same issue with regards to codemasters comment regarding failing builds due to merge conflict of manifest file using Unity 2017.1.1f1

Looking in Temp/StagingArea/android-libraries reveals that 5.0.2 uses:
    
> <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" **android:maxSdkVersion="18"** />

And 5.0.0 uses:

> <uses-permission

 android:name="android.permission.WRITE_EXTERNAL_STORAGE" />

And build failing with:

> Error: [Temp\StagingArea\AndroidManifest-main.xml, C:\Work\Elton\UnityProject\Temp\StagingArea\android-libraries\hockeysdk-unity-5.0.0\AndroidManifest.xml:7] Trying to merge incompatible /manifest/uses-permission[@name=android.permission.WRITE_EXTERNAL_STORAGE] element:
>   <uses-permission
> --    @android:maxSdkVersion="18"
> --    @android:name="android.permission.WRITE_EXTERNAL_STORAGE">
> --</uses-permission>
>   <uses-permission
> ++    @android:name="android.permission.WRITE_EXTERNAL_STORAGE">
> ++</uses-permission>
> ++(end reached)
> ]
> stdout[
> 
> ]
> exit code: 1

Any ETA on updated release (if this indeed the issue?)

**Comment by pleribus** [comment] 2017-10-23 22:17
Just following up.  

Tried a fresh blank project in Unity 2017.1.1f1, importing only hockeyapp package, following install instructions.

Same result.

**Comment by TroubleMakerBen** [comment] 2017-10-24 04:32
Hey folks,

can you guys try using `replace` instead of `remove`?
`<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" tools:node="replace" />`

We've heard from some customers that `remove` is not working from them but `replace` is.

Best,
Benjamin

**Comment by pleribus** [comment] 2017-10-24 05:56
No luck.

I have a skeleton Unity3D 2017.1.1f1 project with just HockeyApp if I can send it directly to you?

Might shed light on if I'm doing something wrong, or if issue lies with current package or SDK tooling

**Comment by MatkovIvan** [comment] 2017-10-24 13:33
@pleribus yes, please share repro sample.
I've tested it again with the last release and still didn't faced this issue.

**Comment by pleribus** [comment] 2017-10-25 00:55
@MatkovIvan Sent that project via email.

You may be onto something regarding Tools versions.

I had to downgrade SDK tools folder to tools_r25.2.5 and JDK to jdk-8u144 on last project. to get around issues with latest JDK and Tools not working with Unity3D 2017.1 on Win10 as mentioned here: 

https://issuetracker.unity3d.com/issues/android-build-fails-when-the-latest-android-sdk-tools-25-dot-3-1-version-is-used

Last post suggests running latest update in Android Studio has perhaps resolved. 

Let me try this and respond as well.

**Comment by MatkovIvan** [comment] 2017-10-25 10:08
@chrwend Thanks.

I confirmed the issue. This only happens on old Android SDK tools. On last `26.1.1` works fine.
Also, I confirm that PR #23 fixes it even with old tools.
So, to avoid this issue update Android SDK tools or wait for release next version of HockeyApp SDK unity wrapper.

@TroubleMakerBen I think we might release patch version for fix this ASAP.

**Comment by delexaet** [comment] 2017-11-03 23:27
@MatkovIvan It seems like the commit was deleted. Any way to get it back so I can use this fix for now? Updating to latest android SDK tools doesn't fix it for me.

**Comment by TroubleMakerBen** [comment] 2017-11-06 18:23
@delexaet The commit was actually merged in #23. The ETA for the next release is early December. Thix for bearing with us. If you want a pre-release binary of the SDK, please ping me at bereimol at microsoft dot com.

**Comment by delexaet** [comment] 2017-11-06 18:39
Ah ok, no problem. We can wait for the december release. Thanks

**Comment by Skjalgsm** [comment] 2017-11-13 13:53
Hi, I would just like to point out that PR #23 does not fix it with old tools. The only thing that fixed it was downloading the latest tools package from https://developer.android.com/studio/index.html?utm_source=android-studio

https://dl.google.com/android/repository/sdk-tools-darwin-3859397.zip

**Comment by TroubleMakerBen** [comment] 2017-12-01 18:39
We've released the update.
I'll make sure to update the docs to say to use the latest Android build tooling.

Thx for the help and patience y'all!

Benjamin

**Closed by TroubleMakerBen** 2017-12-01 18:39 UTC
